"use strict";
exports.__esModule = true;
exports.MessageTags = {
    PAIRING_UPDATE: 'PAIRING_UPDATE',
    APPLICATION_UPDATE: 'APPLICATION_UPDATE',
    ACCOUNT_UPDATE: 'ACCOUNT_UPDATE',
    PAYMENT_UPDATE: 'PAYMENT_UPDATE',
    PERSONAL_FINANCE_UPDATE: 'PERSONAL_FINANCE_UPDATE',
    SHIPPING_UPDATE: 'SHIPPING_UPDATE',
    RESERVATION_UPDATE: 'RESERVATION_UPDATE',
    ISSUE_RESOLUTION: 'ISSUE_RESOLUTION',
    APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
    GAME_EVENT: 'GAME_EVENT',
    TRANSPORTATION_UPDATE: 'TRANSPORTATION_UPDATE',
    FEATURE_FUNCTIONALITY_UPDATE: 'FEATURE_FUNCTIONALITY_UPDATE',
    TICKET_UPDATE: 'TICKET_UPDATE'
};
exports.AddMessageTag = function (message, tag) {
    message.sourceEvent({
        facebook: {
            messaging_type: 'MESSAGE_TAG',
            tag: tag
        }
    });
    return message;
};
